### ISSUE TITLE
works for elywings?

### ISSUE THREAD

**Issue by dries-c** [MC-SG/OriginalSG#3]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* Version:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by remotevase** [comment]
Why not?

**Comment by dries-c** [comment]
there is a setspawn bug he starts 13 and then to 22

Op 24-dec.-2016 15:17 schreef "remote_vase" <notifications@github.com>:

**Comment by remotevase** [comment]
I'm confused. Clarify please

**Comment by dries-c** [comment]
wait

**Comment by remotevase** [comment]
okay i'll wait...
